In [63]:
import numpy as np
X=np.array([[1,1],[1,3],[1,5]])
X

array([[1, 1],
       [1, 3],
       [1, 5]])

In [69]:
Y=np.array([4.8,11.3,17.2]).reshape(-1,1)#This is done to make it 3*2 and in end to get 2 values In[68].If not we will get one value which is may be the intercept and it passes through the origin
Y

array([[ 4.8],
       [11.3],
       [17.2]])

In [70]:
np.linalg.inv(X.T.dot(X))

array([[ 1.45833333, -0.375     ],
       [-0.375     ,  0.125     ]])

In [71]:
np.linalg.inv(X.T.dot(X)).dot(X.T)

array([[ 1.08333333,  0.33333333, -0.41666667],
       [-0.25      ,  0.        ,  0.25      ]])

In [75]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)

array([[1.8],
       [3.1]])

## Model method

In [76]:
X=np.array([1,3,5]).reshape(-1,1)
X

array([[1],
       [3],
       [5]])

In [77]:
Y=np.array([4.8,11.3,17.2])
Y

array([ 4.8, 11.3, 17.2])

In [78]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()

In [79]:
LR.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [80]:
LR.coef_

array([3.1])

In [81]:
LR.intercept_

1.8000000000000025

In [84]:
LR.predict(X)

array([ 4.9, 11.1, 17.3])