In [10]:
Weather=['sunny','rainy','sunny','sunny','sunny','rainy','rainy','sunny','sunny','rainy']
Car=['working','broken','working','working','working','broken','broken','working','broken','broken']
Class=['go-out','go-out','go-out','go-out','go-out','stay-home','stay-home','stay-home','stay-home','stay-home']

In [11]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(Weather)
wheather_encoded

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0], dtype=int64)

In [12]:
car_encoded=le.fit_transform(Car)
label=le.fit_transform(Class)

In [13]:
car_encoded

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [14]:
label

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [23]:
features=zip(weather_encoded,car_encoded)

In [25]:
print(features)

In [19]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,label)

#Predict Output
predicted= model.predict([[0,1]]) # 0:Overcast, 2:Mild
predicted

ValueError: Expected 2D array, got scalar array instead:
array=<zip object at 0x000001A6A0403948>.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.