In [1]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
sec_col=[k[1] for k in mat]
sec_col

[2, 5, 8]

In [3]:
import numpy as np

In [4]:
arr=np.array(mat)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.size

9

In [6]:
arr*100

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [31]:
arr.sum()/arr.size

5.0

In [7]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [8]:
arr+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [9]:
arr+100.66

array([[101.66, 102.66, 103.66],
       [104.66, 105.66, 106.66],
       [107.66, 108.66, 109.66]])

In [10]:
arr/np.pi

array([[0.31830989, 0.63661977, 0.95492966],
       [1.27323954, 1.59154943, 1.90985932],
       [2.2281692 , 2.54647909, 2.86478898]])

In [11]:
np.pi

3.141592653589793

In [12]:
arr**6

array([[     1,     64,    729],
       [  4096,  15625,  46656],
       [117649, 262144, 531441]], dtype=int32)

In [13]:
arr.shape#The output is tuple

(3, 3)

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr=arr.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
nums=[1,2,3,4,5]
arr1d=np.array(nums)
arr1d

array([1, 2, 3, 4, 5])

In [18]:
arr1d.shape

(5,)

In [19]:
RV=arr1d.reshape(1,-1)
RV

array([[1, 2, 3, 4, 5]])

In [20]:
RV.shape

(1, 5)

In [21]:
RV=arr1d.reshape(1,5)
RV

array([[1, 2, 3, 4, 5]])

In [22]:
CV=RV.T
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
CV.shape

(5, 1)

In [24]:
arr1d.mean()

3.0

In [25]:
RV.mean()

3.0

In [26]:
CV.mean()

3.0

In [27]:
arr1d.size

5

In [28]:
RV.size

5

In [29]:
CV.size

5

In [32]:
arr1d.argmax

<function ndarray.argmax>

In [41]:
a=arr1d.argmax()
a

4

In [37]:
CV=arr1d.reshape(-1,1)
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
CV=arr1d.reshape(arr1d.size,1)
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [42]:
a=arr1d.argmin()
a

0

In [44]:
arr=np.random.randint(0,100,16)
arr

array([26, 78, 43, 12, 89, 13, 98, 52, 40, 86, 92, 30, 80,  9, 68, 39])

In [45]:
a=arr1d.T#this will not change

In [46]:
a

array([1, 2, 3, 4, 5])

In [47]:
np.log(10)

2.302585092994046

In [48]:
np.log10(10)

1.0

In [49]:
np.log10(CV)

array([[0.        ],
       [0.30103   ],
       [0.47712125],
       [0.60205999],
       [0.69897   ]])

In [50]:
np.log10(RV)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ]])

In [73]:
np.random.seed(101)#This keeps the random value constant
A=np.random.randint(0,100,16).reshape(4,4)
A

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [74]:
A.shape

(4, 4)

In [75]:
B=A[0].shape

In [76]:
B

(4,)

In [77]:
B=A[0]

In [78]:
B

array([95, 11, 81, 70])

In [79]:
C=A*B

In [80]:
C

array([[9025,  121, 6561, 4900],
       [5985,  957, 6075,  630],
       [7315,  440,  324, 4410],
       [3800,  660, 7452, 4480]])

In [59]:
A=[1,2,3]
B=[10]
C=A+B
C

[1, 2, 3, 10]

In [65]:
nums=[1,2,3,4,5]
arr1d=np.array(nums)

arr1d

array([1, 2, 3, 4, 5])

In [84]:
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [85]:
C+CV#Broadcasting

ValueError: operands could not be broadcast together with shapes (4,4) (5,1) 

In [86]:
A.dot(B)

array([20607, 13647, 12489, 16392])

In [88]:
A.dot(B.reshape(1,-1))

ValueError: shapes (4,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [87]:
A.dot(B.reshape(-1,1))#Built in function

array([[20607],
       [13647],
       [12489],
       [16392]])

In [89]:
np.matmul(A,B.reshape(-1,1))#numpy function

array([[20607],
       [13647],
       [12489],
       [16392]])

In [94]:
X=np.array([1,3,5]).reshape(-1,1)
X

array([[1],
       [3],
       [5]])

In [95]:
Y=np.array([4.8,11.3,17.2])
Y

array([ 4.8, 11.3, 17.2])

In [96]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()

In [97]:
LR.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [98]:
LR.coef_

array([3.1])

In [99]:
LR.intercept_

1.8000000000000025

In [100]:
LR.predict(X)

array([ 4.9, 11.1, 17.3])

## Indexing and NumPy Functions

In [101]:
A[0]

array([95, 11, 81, 70])

In [102]:
A[-1]

array([40, 60, 92, 64])

In [103]:
A[:]

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [104]:
A[1,1]#[row,col] indexing

87

In [105]:
A[1][1]#This is not the right way to do

87

In [109]:
A[-1,:]#All the columns of the last row

array([40, 60, 92, 64])

In [110]:
A[:,1]#All the rows of the second column.For loop is not needed.

array([11, 87, 40, 60])

In [112]:
A[:,:]#Entire matrix

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [113]:
A[:]

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [114]:
A[:3]#First 3 rows.No comma means will return the first three

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63]])

In [115]:
A[1:3,1:3]#Elements in the second and third row,second and third column

array([[87, 75],
       [40,  4]])

In [116]:
A[[1,3],[0,2]]#Index interchanged (1,0) and (3,2) works as coordinate

array([63, 92])

In [117]:
A>50 #Boolean indexing.Array of boolean.

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [120]:
A[A>50]

array([95, 81, 70, 63, 87, 75, 77, 63, 60, 92, 64])

In [119]:
A[(A>50) & (A<80)]

array([70, 63, 75, 77, 63, 60, 64])

In [121]:
A.flatten()#Put everything to 1d, 2d can be converted to 1d

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40,  4, 63, 40, 60, 92, 64])

In [122]:
A.flatten().shape

(16,)

In [123]:
A.ravel().shape#Same as flatten

(16,)

In [124]:
A.trace()#Sum of main diagonal elements

250

In [125]:
A.diagonal()

array([95, 87,  4, 64])

In [126]:
#anti diagonal no direct access method.So flip the matrix
#lr left to right
np.fliplr(A).diagonal()

array([70, 75, 40, 40])

In [128]:
#ud up down
np.flipud(A).diagonal()

array([40, 40, 75, 70])

In [129]:
v=[1,2,3,4,5]
np.diag(v)#Quickly create a diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [130]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [134]:
np.zeros((5,3))#5 rows 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
np.zeros(A.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.ones(A.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
np.ones(A.shape)*np.nan

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [139]:
np.nan#nan not a number

nan

In [142]:
np.eye(4)#Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
A.dot(np.eye(A.shape[0]))

array([[95., 11., 81., 70.],
       [63., 87., 75.,  9.],
       [77., 40.,  4., 63.],
       [40., 60., 92., 64.]])

In [150]:
#Even doing A.T will not change the below 4 cell values

In [146]:
A.min()#Returns the min value

4

In [147]:
A.argmin()#Returns the min value position

10

In [148]:
A.max()#Returns the max value

95

In [149]:
A.argmax()#Returns the max value position

0

In [160]:
A1=A[:3,:2]
A1#Counted in -> way

array([[95, 11],
       [63, 87],
       [77, 40]])

In [161]:
A1.min(),A1.argmin()

(11, 1)

In [162]:
A.mean(),A.std(),A.var().round(2)

(58.1875, 28.45219400591104, 809.53)

In [163]:
np.sin(A)#Sine

array([[ 0.68326171, -0.99999021, -0.62988799,  0.77389068],
       [ 0.1673557 , -0.82181784, -0.38778164,  0.41211849],
       [ 0.99952016,  0.74511316, -0.7568025 ,  0.1673557 ],
       [ 0.74511316, -0.30481062, -0.77946607,  0.92002604]])

In [167]:
np.sin(A).round(2)#Round to 2 decimal values

array([[ 0.68, -1.  , -0.63,  0.77],
       [ 0.17, -0.82, -0.39,  0.41],
       [ 1.  ,  0.75, -0.76,  0.17],
       [ 0.75, -0.3 , -0.78,  0.92]])

In [166]:
np.log10(A)#log 10

array([[1.97772361, 1.04139269, 1.90848502, 1.84509804],
       [1.79934055, 1.93951925, 1.87506126, 0.95424251],
       [1.88649073, 1.60205999, 0.60205999, 1.79934055],
       [1.60205999, 1.77815125, 1.96378783, 1.80617997]])

In [168]:
np.exp(A)#e^A

array([[1.81123908e+41, 5.98741417e+04, 1.50609731e+35, 2.51543867e+30],
       [2.29378316e+27, 6.07603023e+37, 3.73324200e+32, 8.10308393e+03],
       [2.75851345e+33, 2.35385267e+17, 5.45981500e+01, 2.29378316e+27],
       [2.35385267e+17, 1.14200739e+26, 9.01762841e+39, 6.23514908e+27]])

In [173]:
list(range(0,10,2))#Goes one before the stop index
type(list(range(0,10,2)))#Output is list

list

In [174]:
np.arange(0,10,2)#Output is a numpy array

array([0, 2, 4, 6, 8])

In [175]:
np.arange(0,10,2.5)#This can take decimal value also as increment

array([0. , 2.5, 5. , 7.5])

In [176]:
np.linspace(0,10,25)#Both the numbers are inclusive and generate 25 numbers.It will generate 23 numbers as two numbers are inclusive.Default number generation is 50.

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [180]:
np.linspace(0,10,25).reshape(5,5).round(2)

array([[ 0.  ,  0.42,  0.83,  1.25,  1.67],
       [ 2.08,  2.5 ,  2.92,  3.33,  3.75],
       [ 4.17,  4.58,  5.  ,  5.42,  5.83],
       [ 6.25,  6.67,  7.08,  7.5 ,  7.92],
       [ 8.33,  8.75,  9.17,  9.58, 10.  ]])

In [182]:
np.logspace(0,3,10).round(2)#10^0 and 10^3 and 8 more numbers both inclusive
#Default number generation is 50.

array([   1.  ,    2.15,    4.64,   10.  ,   21.54,   46.42,  100.  ,
        215.44,  464.16, 1000.  ])